# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title compute_tax_distance
#' @description
#' Modify a string in Rcpp.
#' @name compute_tax_distance
#'
#' @export
compute_tax_distance <- function(tax_file_name) {
    invisible(.Call(`_metataxa_compute_tax_distance`, tax_file_name))
}

timesTwo <- function(x) {
    .Call(`_metataxa_timesTwo`, x)
}

#' @title myFunction
#' @description
#' Modify a string in Rcpp.
#' @name myFunction
#' @param x a vector of strings
#' @examples
#' myFunction(x=c('Hello', "C++", 'header', 'files'))
#'
#' @export
myFunction <- function(x) {
    .Call(`_metataxa_myFunction`, x)
}

